In [1]:
import tensorflow, tensorflow_probability
print(tensorflow.__version__)
print(tensorflow.keras.__version__)
print(tensorflow_probability.__version__)

2.3.0
2.4.0
0.11.0


In [2]:
import tensorflow as tf
import tensorflow_probability as tfp


dist = tfp.distributions.Normal(loc=0., scale=1.)

tf.distributions.Normal will give you a distribution object from which you can sample. https://stackoverflow.com/a/56419842

In [3]:
dist

<tfp.distributions.Normal 'Normal' batch_shape=[] event_shape=[] dtype=float32>

In [4]:
x = tf.random.normal(shape=(3,3))

In [5]:
dist.log_prob(x)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.91900104, -0.9610319 , -2.9530911 ],
       [-1.0733263 , -1.2221428 , -0.95002335],
       [-0.9369619 , -1.17934   , -1.053124  ]], dtype=float32)>

In [6]:
import numpy as np
np.log(dist.prob(x))

array([[-0.9190011 , -0.9610319 , -2.9530911 ],
       [-1.0733263 , -1.2221428 , -0.95002335],
       [-0.93696195, -1.1793401 , -1.0531241 ]], dtype=float32)